version: '3.3'
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - nginx
  db:
    image: postgres:15.2-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_value:/app/static/
      - ./create_superuser.sh:/app/create_superuser.sh:ro
    depends_on:
      - db
    env_file:
      - ./.env
    entrypoint: /app/entrypoint.sh
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static/
    depends_on:
      - web
volumes:
  static_value:
